# ReProSeg with DeepLab v3 backbone configuration

# Network
backbone_network: deeplab_v3

# Network Parameters
num_prototypes: 0  # Use backbone output channels
bias: false

disable_pretrained: false
train_backbone_during_pretrain: false

# Loss configuration
criterion: dice

loss_weights:
  align: 1.0
  jsd: 1.0
  tanh: 0.1
  unif: 0.0
  variance: 0.0
  classification: 10.0