experimentName: reproseg_hyperopt
trialCommand: python /home/annamari/ReProSeg/src/scripts/run.py 
# TODO: (not high priority) read path somehow from .env
trialCodeDirectory: .
trialConcurrency: 1
maxTrialNumber: 20
searchSpaceFile: search_space.json
tuner:
  name: TPE
  classArgs:
    optimize_mode: maximize
assessor:
  name: Medianstop
  classArgs:
    optimize_mode: maximize
    start_step: 70   
trainingService:
  platform: local
